In [198]:
import requests
from xml.etree import ElementTree as ET
import json
import pandas as pd
import ast
import numpy as np

In [184]:
r = requests.get("https://scsanctions.un.org/resources/xml/en/consolidated.xml")

In [185]:
# Get all the tags in the XML
root = ET.fromstring(r.text)
tags = [children.tag for children in root.find("INDIVIDUALS/INDIVIDUAL")]
mapValues: dict = {}
for item in tags:
    mapValues[item] = None

In [221]:
individuals: list = root.findall("INDIVIDUALS/INDIVIDUAL")

def parse_xml(element, item):
    for child in element:
        if len(child) == 0:
            if child.tag in item:
                if not isinstance(item[child.tag], list):
                    item[child.tag] = [item[child.tag]]
                item[child.tag].append(child.text)
            else:
                item[child.tag] = child.text
        else:
            if child.tag not in item:
                item[child.tag] = []
            sub_item = {}
            parse_xml(child, sub_item)
            item[child.tag].append(sub_item)

parsed_data = {}
parse_xml(individuals, parsed_data)

In [248]:
df = pd.DataFrame(parsed_data['INDIVIDUAL'])

In [249]:
def first_name(df):
    name = df['FIRST_NAME'].fillna('') + ' ' + df['SECOND_NAME'].fillna('') + ' ' + df['THIRD_NAME'].fillna('') + ' ' + df['FOURTH_NAME'].fillna('')
    return name.apply(lambda x: x.strip())

df['FULL_NAME'] = first_name(df)

In [277]:
def parse_dates(row):
    year  = []
    death = []
    if len(row) == 0:
        pass
    for item in row:
        if 'YEAR' in item:
            year.append(item['YEAR'])
        if 'FROM_YEAR' in item:
            year.append(item['FROM_YEAR'])
        if 'TO_YEAR' in item:
            death.append(item['TO_YEAR'])

    return year, death

            
            

df['INDIVIDUAL_DATE_OF_BIRTH'] = [ [] if x is np.NaN else x for x in df['INDIVIDUAL_DATE_OF_BIRTH'] ]
df['birth_date'], df['death_date'] = zip(*df['INDIVIDUAL_DATE_OF_BIRTH'].copy().apply(lambda x: parse_dates(x)))
df
#df[df['INDIVIDUAL_DATE_OF_BIRTH'] == '']
#dict_keys(['TYPE_OF_DATE', 'FROM_YEAR', 'TO_YEAR'])
#df['INDIVIDUAL_DATE_OF_BIRTH'].apply(lambda x: [print(item.keys()) for item in x])

,DATAID,VERSIONNUM,FIRST_NAME,SECOND_NAME,THIRD_NAME,UN_LIST_TYPE,REFERENCE_NUMBER,LISTED_ON,NAME_ORIGINAL_SCRIPT,COMMENTS1,...,INDIVIDUAL_PLACE_OF_BIRTH,INDIVIDUAL_DOCUMENT,SORT_KEY,SORT_KEY_LAST_MOD,GENDER,FOURTH_NAME,FULL_NAME,birth_date,death,death_date
0,110447,1,MUHAMMAD,TAHER,ANWARI,Taliban,TAi.005,2001-02-23,Ù Ø­Ù Ø¯ Ø·Ø§ÙØ± Ø£ÙÙØ±Ù,Belongs to Andar tribe. Review pursuant to Sec...,...,"[{'CITY': 'Zurmat District', 'STATE_PROVINCE':...",None,None,None,NaN,NaN,MUHAMMAD TAHER ANWARI,[1961],[],[]
1,110554,1,ABDUL LATIF,MANSUR,NaN,Taliban,TAi.007,2001-01-31,Ø¹Ø¨Ø¯ Ø§ÙÙØ·ÙÙ Ù ÙØµÙØ±,Taliban Shadow Governor for Logar Province as ...,...,"[{'CITY': 'Zurmat District', 'STATE_PROVINCE':...",None,None,None,NaN,NaN,ABDUL LATIF MANSUR,[1968],[],[]
2,110578,1,ABDUL KABIR,MOHAMMAD JAN,NaN,Taliban,TAi.003,2001-01-25,Ø¹Ø¨Ø¯ Ø§ÙÚ©Ø¨ÛØ± Ù Ø­Ù Ø¯ Ø¬Ø§Ù,Active in terrorist operations in Eastern Afgh...,...,[{'CITY': 'Pul-e-Khumri or Baghlan Jadid Distr...,None,None,None,NaN,NaN,ABDUL KABIR MOHAMMAD JAN,[1963],[],[]
3,110579,1,MOHAMMED,OMAR,GHULAM NABI,Taliban,TAi.004,2000-04-12,Ù Ø­Ù Ø¯ Ø¹Ù Ø± ØºÙØ§Ù ÙØ¨Û,"Father's name is Ghulam Nabi, also known as Mu...",...,"[{'CITY': 'Naw Deh village, Deh Rawud District...",None,None,None,NaN,NaN,MOHAMMED OMAR GHULAM NABI,[1966],[],[]
4,110580,1,SAYYED MOHAMMED,HAQQANI,NaN,Taliban,TAi.006,2001-01-31,Ø³ÙØ¯ Ù Ø­Ù Ø¯ Ø­ÙØ§ÙÛ,Graduate of the Haqqaniya madrasa in Akora Kha...,...,"[{'CITY': 'Chaharbagh village, Arghandab Distr...",None,None,None,NaN,NaN,SAYYED MOHAMMED HAQQANI,[1965],[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681,6909274,1,PROPHANE,VICTOR,NaN,Haiti,HTi.006,2024-09-27,NaN,Gender: Male.,...,[{'COUNTRY': None}],None,None,None,NaN,NaN,PROPHANE VICTOR,[],[],[]
682,6909275,1,LUCKSON,ELAN,NaN,Haiti,HTi.007,2024-09-27,NaN,Gender: Male.,...,[{'COUNTRY': None}],None,None,None,NaN,NaN,LUCKSON ELAN,[],[],[]
683,2894441,1,MUTHANNA,HARITH,SALMAN,Al-Qaida,QDi.278,2010-03-25,Ù Ø«ÙÙ Ø­Ø§Ø±Ø« Ø³ÙÙ Ø§Ù Ø§ÙØ¶Ø§Ø±Ù,Motherâs name: Heba Khamis Dari. Fatherâs ...,...,[{'COUNTRY': 'Iraq'}],[{'TYPE_OF_DOCUMENT': 'National Identification...,None,None,NaN,AL-DARI,MUTHANNA HARITH SALMAN AL-DARI,[],[],[]
684,6908417,1,MAYSAR ALI,MUSA,ABDALLAH,Al-Qaida,QDi.337,2014-09-23,NaN,Sharia amir of Al-Nusrah Front for the People ...,...,"[{'CITY': 'Al-Shura', 'STATE_PROVINCE': 'Mosul...",None,None,None,NaN,AL-JUBURI,MAYSAR ALI MUSA ABDALLAH AL-JUBURI,[1976],[],[]
685,6908658,1,SALIM,MUSTAFA,MUHAMMAD,Al-Qaida,QDi.411,2018-03-06,Ø³Ø§ÙÙ Ù ØµØ·ÙÙ Ù Ø­Ù Ø¯ Ø§Ù Ù ÙØµÙØ±,: Finance âemirâ for Islamic State in Iraq...,...,"[{'CITY': 'Baghdad', 'COUNTRY': 'Iraq'}, {'CIT...","[{'TYPE_OF_DOCUMENT': 'Passport', 'NUMBER': 'A...",None,None,NaN,AL-MANSUR,SALIM MUSTAFA MUHAMMAD AL-MANSUR,[1959],[],[]

url = "https://api.pocketbase.io/v1/databases/<your-database-id>/collections/<your-collection>"
headers = {"Content-Type": "application/json", "Authorization": "<your-api-key>"}
data = {"name": "Sameer", "age": 23}
response = requests.post(url, headers=headers, data=json.dumps(data))
if response.status_code == 201:
    print("Data stored successfully!")
else:
    print("Failed to store data")